name: pkgcheck

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  pkgcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pkgcore/pkgcheck-action@v1
